# helm-values/consul-values.yaml

# This is a minimal configuration to get Consul running
# and bypass the Ingress error.

server:
  replicas: 1

ui:
  enabled: true
  ingress:
    enabled: false # <--- This line prevents the problematic template from running