# helm-values/consul-values.yaml

# Configuration for Consul as Vault storage backend
server:
  replicas: 3
  bootstrap: true
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

global:
  name: consul
  acls:
    manageSystemACLs: true
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    enableAutoEncrypt: true

ui:
  enabled: true
  ingress:
    enabled: false

client:
  enabled: true
  grpc: true
